import{S as u,i as l}from"./assets/vendor-96ed78f5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const g=document.querySelector(".gallery");function y(o,s,n,a,e,t,r){const c=`<li class="gallery-item">
      <a class="gallery-link" href="${s}">
      <img src="${o}" alt="${n}" class="gallery-img">
      </a>
        <div class="text-wrap">
          <p class="img-text">Likes <span class="img-text-span">${a}</span></p>
          <p class="img-text">Views <span class="img-text-span">${e}</span></p>
          <p class="img-text">Comments <span class="img-text-span">${t}</span></p>
          <p class="img-text">Downloads <span class="img-text-span">${r}</span></p>
        </div>
    </li>`;g.insertAdjacentHTML("afterbegin",c),new u(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250}).on("show.simplelightbox",function(){})}function h(o){return fetch(`https://pixabay.com/api/?key=44806225-40e07737f22f709bd193bb0f7&q=${o}&image_type=photo&orientation=horizontal&safesearch=${!0}`).then(r=>{if(!r.ok)throw new Error("no match item");return r.json()})}const i=document.querySelector(".loader");i.style.opacity=0;const d=document.querySelector(".btn");d.addEventListener("click",b);function b(){i.style.opacity=1}const m=document.querySelector(".form");m.addEventListener("submit",S);function S(o){o.preventDefault();const n=o.currentTarget.elements.query.value.toLowerCase();if(n.length<=0){l.show({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Please write something in the search field"}),i.style.opacity=0;return}setTimeout(()=>{h(n).then(x).catch(w)},1e3),m.reset()}function x(o){const s=o.hits;o.totalHits===0?l.error({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):s.map(({webformatURL:a,largeImageURL:e,tags:t,likes:r,views:c,comments:p,downloads:f})=>{y(a,e,t,r,c,p,f)}),i.style.opacity="0"}function w(){l.error({backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16px",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}
//# sourceMappingURL=commonHelpers.js.map
